[package]
name = "axum-start"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
# Serde / json
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Axum
axum = "0.7"


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"